# Generated by Django 5.0.6 on 2024-06-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlecture',
            name='status',
            field=models.CharField(choices=[('pass', 'پاس'), ('fail', 'رد'), ('no status', 'داده خالی')], default='pass'),
        ),
    ]
