# Generated by Django 5.0.6 on 2024-07-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_studentlecture_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='title',
        ),
        migrations.AddField(
            model_name='lecture',
            name='day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
